name: Backend

on: [push, pull_request]

jobs:
  backend-install-dependencies-ubunut:
    name: Install dependencies ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Run dpendencie script
      run: |
        ./install_dependencies.sh

  backend-install-development-dependencies-ubunut:
    name: Install development dependencies ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Run dpendencie script
      run: |
        ./install_dependencies_development.sh

  backend-install-dependencies-mac:
    name: Install dependencies mac
    runs-on: macos-12 
    steps:
    - name: Install brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Run dpendencie script
      run: |
        ./install_dependencies.sh

  backend-install-development-dependencies-mac:
    name: Install development dependencies mac
    runs-on: macos-12 
    steps:
    steps:
    - name: Install brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Run dpendencie development script
      run: |
        ./install_dependencies_development.sh

  backend-test-and-lint:
    name: Backend Test and Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install libpq PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install pipenv virtual environment with dev dependencies
      run: |
        pipenv sync --dev
    - name: Run all pre-commit hooks
      uses: pre-commit/action@v2.0.0
    - name: Run all python tests
      run: |
        pipenv run pytest tests/ --cov=hyrisecockpit --cov-fail-under=75
    - name: Native requirements mirror pipenv requirements
      run: |
        pipenv run pipenv_to_requirements -o requirements_temp.txt -f && cmp -s requirements.txt requirements_temp.txt
    - name: Native requirements-dev mirror pipenv-dev requirements
      run: |
        pipenv run pipenv_to_requirements -d requirements-dev_temp.txt -f && cmp -s requirements-dev.txt requirements-dev_temp.txt