name: Backend Lint and Test

on: [push, pull_request]

jobs:
  build-pipenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1
    - name: Install libpq PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install pipenv virtual environment with dev dependencies
      run: |
        pipenv sync --dev
    - name: Run all pre-commit hooks
      run: |
        pipenv run pre-commit run --all-files
    - name: Run all python tests
      run: |
        pipenv run pre-commit run --hook-stage manual pytest
  build-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1
    - name: Install libpq PostgreSQL client
      run: sudo apt-get -yqq install libpq-dev
    - name: Install dev dependencies
      run: |
        pip install -r requirements-dev.txt
    - name: Run all pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Run all python tests
      run: |
        pre-commit run --hook-stage manual pytest